const Airlines = [
  {
    company: "Türk Hava Yolları",
    icon_url:
      "https://elissatur.com.tr/wp-content/uploads/2015/07/turkish-airlines-logo-1024x690.png",
    kapasite: "20",
  },
  {
    company: "Pegasus",
    icon_url:
      "https://www.hindistanhavayollari.gen.tr/wp-content/uploads/2019/06/pegasus-airlines-1.png",
    kapasite: "20",
  },
];

const FlightsData = [
  {
    id: 1,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "630TL",
    tarih: "2022-06-24",
    kalkis_saati: "10:00",
    inis_saati: "12:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 2,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "670TL",
    tarih: "2022-06-24",
    kalkis_saati: "15:00",
    inis_saati: "17:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 3,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "580TL",
    tarih: "2022-06-24",
    kalkis_saati: "21:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 4,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "655TL",
    tarih: "2022-06-24",
    kalkis_saati: "11:00",
    inis_saati: "13:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 5,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "720TL",
    tarih: "2022-06-24",
    kalkis_saati: "16:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 6,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "665TL",
    tarih: "2022-06-24",
    kalkis_saati: "20:00",
    inis_saati: "22:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 7,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "640TL",
    tarih: "2022-06-24",
    kalkis_saati: "09:00",
    inis_saati: "11:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 8,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "780TL",
    tarih: "2022-06-24",
    kalkis_saati: "13:00",
    inis_saati: "15:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 9,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "640TL",
    tarih: "2022-06-24",
    kalkis_saati: "18:00",
    inis_saati: "20:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 10,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "500TL",
    tarih: "2022-06-24",
    kalkis_saati: "08:00",
    inis_saati: "10:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 11,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "780TL",
    tarih: "2022-06-24",
    kalkis_saati: "16:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 12,
    from: "İstanbul",
    to: "Ankara",
    fiyat: "620TL",
    tarih: "2022-06-24",
    kalkis_saati: "21:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 13,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "550TL",
    tarih: "2022-06-24",
    kalkis_saati: "09:00",
    inis_saati: "10:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 14,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "590TL",
    tarih: "2022-06-24",
    kalkis_saati: "14:00",
    inis_saati: "15:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 15,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "540TL",
    tarih: "2022-06-24",
    kalkis_saati: "21:00",
    inis_saati: "22:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 16,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "620TL",
    tarih: "2022-06-24",
    kalkis_saati: "11:00",
    inis_saati: "12:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 17,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "620TL",
    tarih: "2022-06-24",
    kalkis_saati: "17:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 18,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "620TL",
    tarih: "2022-06-24",
    kalkis_saati: "22:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 19,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "550TL",
    tarih: "2022-06-24",
    kalkis_saati: "09:00",
    inis_saati: "10:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 20,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "590TL",
    tarih: "2022-06-24",
    kalkis_saati: "14:00",
    inis_saati: "15:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 21,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "540TL",
    tarih: "2022-06-24",
    kalkis_saati: "21:00",
    inis_saati: "22:00",
    kalkis_havaalani: "Atatürk Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 22,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "530TL",
    tarih: "2022-06-24",
    kalkis_saati: "11:00",
    inis_saati: "12:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 23,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "620TL",
    tarih: "2022-06-24",
    kalkis_saati: "17:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 24,
    from: "İstanbul",
    to: "İzmir",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "22:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Sabiha Gökçen Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 25,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "10:00",
    inis_saati: "11:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 26,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "680TL",
    tarih: "2022-06-24",
    kalkis_saati: "15:00",
    inis_saati: "16:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 27,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "13:00",
    inis_saati: "14:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 28,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "22:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 29,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "580TL",
    tarih: "2022-06-24",
    kalkis_saati: "12:00",
    inis_saati: "13:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 30,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "650TL",
    tarih: "2022-06-24",
    kalkis_saati: "22:00",
    inis_saati: "23:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 31,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "490TL",
    tarih: "2022-06-24",
    kalkis_saati: "07:00",
    inis_saati: "08:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 32,
    from: "İzmir",
    to: "İstanbul",
    fiyat: "630TL",
    tarih: "2022-06-24",
    kalkis_saati: "18:00",
    inis_saati: "19:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 33,
    from: "İzmir",
    to: "Ankara",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "12:00",
    inis_saati: "13:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 34,
    from: "İzmir",
    to: "Ankara",
    fiyat: "630TL",
    tarih: "2022-06-24",
    kalkis_saati: "18:00",
    inis_saati: "19:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 35,
    from: "İzmir",
    to: "Ankara",
    fiyat: "450TL",
    tarih: "2022-06-24",
    kalkis_saati: "09:00",
    inis_saati: "10:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 36,
    from: "İzmir",
    to: "Ankara",
    fiyat: "520TL",
    tarih: "2022-06-24",
    kalkis_saati: "17:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Adnan Menderes Havalimanı",
    inis_havaalani: "Esenboğa Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 37,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "450TL",
    tarih: "2022-06-24",
    kalkis_saati: "10:00",
    inis_saati: "12:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 38,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "610TL",
    tarih: "2022-06-24",
    kalkis_saati: "15:00",
    inis_saati: "17:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 39,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "440TL",
    tarih: "2022-06-24",
    kalkis_saati: "10:00",
    inis_saati: "12:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 40,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "560TL",
    tarih: "2022-06-24",
    kalkis_saati: "16:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 41,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "480TL",
    tarih: "2022-06-24",
    kalkis_saati: "11:00",
    inis_saati: "13:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 42,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "20:00",
    inis_saati: "22:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Sabiha Gökçen Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 43,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "540TL",
    tarih: "2022-06-24",
    kalkis_saati: "13:00",
    inis_saati: "15:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 44,
    from: "Ankara",
    to: "İstanbul",
    fiyat: "570TL",
    tarih: "2022-06-24",
    kalkis_saati: "18:00",
    inis_saati: "20:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Atatürk Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 45,
    from: "Ankara",
    to: "İzmir",
    fiyat: "440TL",
    tarih: "2022-06-24",
    kalkis_saati: "10:00",
    inis_saati: "11:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 46,
    from: "Ankara",
    to: "İzmir",
    fiyat: "550TL",
    tarih: "2022-06-24",
    kalkis_saati: "17:00",
    inis_saati: "18:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[0].company,
    ikon: Airlines[0].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 47,
    from: "Ankara",
    to: "İzmir",
    fiyat: "180TL",
    tarih: "2022-06-24",
    kalkis_saati: "12:00",
    inis_saati: "13:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
  {
    id: 48,
    from: "Ankara",
    to: "İzmir",
    fiyat: "580TL",
    tarih: "2022-06-24",
    kalkis_saati: "20:00",
    inis_saati: "21:00",
    kalkis_havaalani: "Esenboğa Havalimanı",
    inis_havaalani: "Adnan Menderes Havalimanı",
    firma: Airlines[1].company,
    ikon: Airlines[1].icon_url,
    koltukar: [
      { id: 1, alinabilir: 1 },
      { id: 2, alinabilir: 1 },
      { id: 3, alinabilir: 0 },
      { id: 4, alinabilir: 1 },
      { id: 5, alinabilir: 0 },
      { id: 6, alinabilir: 0 },
      { id: 7, alinabilir: 1 },
      { id: 8, alinabilir: 0 },
      { id: 9, alinabilir: 1 },
      { id: 10, alinabilir: 1 },
      { id: 11, alinabilir: 1 },
      { id: 12, alinabilir: 1 },
      { id: 13, alinabilir: 0 },
      { id: 14, alinabilir: 1 },
      { id: 15, alinabilir: 0 },
      { id: 16, alinabilir: 0 },
      { id: 17, alinabilir: 1 },
      { id: 18, alinabilir: 0 },
      { id: 19, alinabilir: 1 },
      { id: 20, alinabilir: 1 },
    ],
  },
];

export default FlightsData;
